name: Bug report
description: Something isn’t working
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Include steps to reproduce and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste `monitorctl doctor` output and any relevant errors.
      render: shell

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS 15.x / Windows 11 / ...
    validations:
      required: true

  - type: input
    id: monitor
    attributes:
      label: Monitor model(s)
      placeholder: ASUS XG27ACS / ...
    validations:
      required: true

  - type: input
    id: connection
    attributes:
      label: Connection type
      placeholder: USB‑C / DisplayPort / HDMI (direct vs dock/hub)
    validations:
      required: true
